apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkpulse-api
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: linkpulse-api
  template:
    metadata:
      labels:
        app: linkpulse-api
    spec:
      containers:
        - name: linkpulse-docker
          image: asia-east1-docker.pkg.dev/linkpulse-508704/linkpulse-repo/linkpulse:ece052613b74472c73bfa74f32b6f4631790fd19
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: 
                name: linkpulse-api
            - secretRef: 
                name: linkpulse-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"